name: CI/CD for Dine App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t dineshkumarv1/dine-frontend:latest ./dine/frontend
        docker push dineshkumarv1/dine-frontend:latest

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t dineshkumarv1/dine-backend:latest ./dine/backend
        docker push dineshkumarv1/dine-backend:latest

    - name: SSH and Deploy on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_SSH }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Navigate to the application directory on the EC2 instance
          cd ~/dinesh/DevOps-project/DevOps-project/dine

          # Pull the latest Docker images
          docker-compose pull

          # Bring down any running containers
          docker-compose down

          # Start the containers in detached mode
          docker-compose up -d

